name: Deploy Site

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: make
        id: compile
        name: Run Makefile (copy site all/only the listed site components)

      - id: deploy
        continue-on-error: true
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_KEY }}
          dist_dir: _site
          cleanup: true

      - name: Deploy to Neocities fallback
        if: ${{ steps.deploy.outcome == 'failure' }}
        uses: jonchang/deploy-neocities@master
        with:
          key: ${{ secrets.NEOCITIES_API_KEY }}
          dir: _site
          clean: true
