name: Deploy Site

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - if: ${{ success() && github.ref == 'main'}}
        name: Compile Website
        run: make

      - if: ${{ success() && github.ref == 'main'}}
        name: Deploy to Neocities
        id: deploy
        continue-on-error: true
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_KEY }}
          dist_dir: _site
          cleanup: true

      - name: Deploy to Neocities (fallback)
        if: ${{ steps.deploy.outcome == 'failure' && github.ref == 'refs/heads/deployed' }}
        uses: jonchang/deploy-neocities@master
        with:
          key: ${{ secrets.NEOCITIES_API_KEY }}
          dir: _site
          clean: true
